/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import DAO.ClienteDAO;
import DAO.SalidaDAO;
import Modelo.Cliente;
import Modelo.Salida;
import Modelo.Iva;
import java.util.List;
import Modelo.Usuario;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class formRegistroSalidasAdd extends javax.swing.JFrame {

    Usuario sysUser;
    /**
     * Creates new form formUsuarioAdd
     */
    public formRegistroSalidasAdd() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public formRegistroSalidasAdd(Usuario user) {
        initComponents();
        this.sysUser = user;
        this.setLocationRelativeTo(null);
        this.getPorcentaje();
        this.getCliente();
    }
     public void getCliente(){
        ClienteDAO ClienDAO = new ClienteDAO();
        List<Cliente> client = ClienDAO.listar();

        jtxCliente.removeAllItems();
        for(Cliente cli:client){
            jtxCliente.addItem(new Cliente(cli.getIdCliente(), cli.getPrimerApellido()));
            //jtxentrada.addItem(new Proveedor(String.valueOf(pro.getIdProveedor()), String.valueOf(pro.getPrimerNombre())));
        }
        
    }
     public void getPorcentaje(){
        
        listIVA.removeAllItems();
        listIVA.addItem(new Iva("0%",1));
        listIVA.addItem(new Iva("12%",2));
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        labTitle = new javax.swing.JLabel();
        labcodigo = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        labidcliente = new javax.swing.JLabel();
        labFecha = new javax.swing.JLabel();
        labsubTotal = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        labIva = new javax.swing.JLabel();
        labtotal = new javax.swing.JLabel();
        txtTOTAL = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        txtFecha2 = new javax.swing.JFormattedTextField();
        listIVA = new javax.swing.JComboBox<>();
        jtxCliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panMain.setBackground(new java.awt.Color(255, 255, 255));
        panMain.setForeground(new java.awt.Color(255, 255, 255));
        panMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labTitle.setForeground(new java.awt.Color(11, 58, 82));
        labTitle.setText("Registrar Salida");
        panMain.add(labTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        labcodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labcodigo.setText("Codigo");
        panMain.add(labcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtCod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCod.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        panMain.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, 30));

        labidcliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labidcliente.setText("ID Cliente");
        panMain.add(labidcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        labFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labFecha.setText("Fecha");
        panMain.add(labFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        labsubTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labsubTotal.setText("SubTotal");
        panMain.add(labsubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        txtSubtotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubtotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });
        panMain.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 180, 30));

        labIva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labIva.setText("Iva");
        panMain.add(labIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        labtotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labtotal.setText("Total");
        panMain.add(labtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        txtTOTAL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTOTAL.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTOTALActionPerformed(evt);
            }
        });
        panMain.add(txtTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 190, 30));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("Cancelar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panMain.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 90, 30));

        btnGuardar1.setBackground(new java.awt.Color(11, 58, 82));
        btnGuardar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setText("Guardar");
        btnGuardar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        panMain.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 90, 30));

        txtFecha2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtFecha2.setText("dd/MM/yyyy");
        txtFecha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFecha2ActionPerformed(evt);
            }
        });
        panMain.add(txtFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 170, 30));

        listIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listIVAActionPerformed(evt);
            }
        });
        panMain.add(listIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 30));

        jtxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxClienteActionPerformed(evt);
            }
        });
        panMain.add(jtxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTOTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTOTALActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        
        Salida entra = new Salida();
        SalidaDAO EntraDAO = new SalidaDAO();
        
        if(!txtCod.getText().equals("") && 
                !txtFecha2.getText().equals("") && !txtSubtotal.getText().equals("") &&
                !txtTOTAL.getText().equals("") ){
            
            entra.setCodigo((String)txtCod.getText());
              entra.setIdCliente(String.valueOf(jtxCliente.getItemAt(jtxCliente.getSelectedIndex()).getIdCliente()));
            //entra.setIdCliente(String.valueOf(txtClien.getText()));
            entra.setSubtotal(Float.parseFloat(txtSubtotal.getText()));
            entra.setValorIva((int) listIVA.getItemAt(listIVA.getSelectedIndex()).getValor());
            entra.setTotal(Float.parseFloat(txtTOTAL.getText()));
            LocalDate fecha = LocalDate.parse(txtFecha2.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy")); 
            entra.setFechaSalida(fecha);

            
            if(entra.getCodigo().length() > 4 && entra.getCodigo().length() <= 5){
                
                if(entra.getIdCliente().length() >= 1){
                    if(entra.getIdCliente().length() <= 11){

                       entra.setEstado(1);
                        entra.setFechaIngreso(LocalDateTime.now());
                        entra.setUsuarioIngreso(sysUser.getUsername());
                            
                        if(EntraDAO.registrar(entra)){                           
                            this.dispose();
                            formRegistroSalidas.getS();

                        }else{
                            JOptionPane.showMessageDialog(null, "No se guradaron los datos.");
                        }
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "El id del provedor debe de ser de 1 caracter maximo 11.");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "El id del provedor debe de ser de 1 caracter maximo 11.");
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "El codigo deber tener 5 caracteres.");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos del formulario.");
        }
        
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void txtFecha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecha2ActionPerformed

    private void listIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listIVAActionPerformed

    private void jtxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formRegistroSalidasAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formRegistroSalidasAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formRegistroSalidasAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formRegistroSalidasAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRegistroSalidasAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JComboBox<Cliente> jtxCliente;
    private javax.swing.JLabel labFecha;
    private javax.swing.JLabel labIva;
    private javax.swing.JLabel labTitle;
    private javax.swing.JLabel labcodigo;
    private javax.swing.JLabel labidcliente;
    private javax.swing.JLabel labsubTotal;
    private javax.swing.JLabel labtotal;
    private javax.swing.JComboBox<Modelo.Iva> listIVA;
    private javax.swing.JPanel panMain;
    private javax.swing.JTextField txtCod;
    private javax.swing.JFormattedTextField txtFecha2;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTOTAL;
    // End of variables declaration//GEN-END:variables
}
