/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import DAO.ClienteDAO;
import DAO.SalidaDAO;
import Modelo.Cliente;
import Modelo.Salida;
import DAO.EntradaDAO;
import DAO.ProveedorDAO;
import Modelo.Proveedor;
import Modelo.Entrada;
import Modelo.Iva;
import Modelo.Usuario;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class formRegistroSalidasEdit extends javax.swing.JFrame {

    Usuario sysUser;
    String identra;
    String idCliente;
    /**
     * Creates new form formUsuarioAdd
     */
    public formRegistroSalidasEdit() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public formRegistroSalidasEdit(String id, Usuario user) {
        initComponents();
        this.sysUser = user;
        this.identra = id;
        this.setLocationRelativeTo(null);
        this.getPorcentaje();
        this.getDatosProducto();
        this.getCliente();
    }
    

    public void getDatosProducto(){
        
        Salida entra = new Salida();
        SalidaDAO entraDAO = new SalidaDAO();
        
        System.out.println(identra);
        entra = entraDAO.leer(Integer.parseInt(identra));
        
        txtcodigo.setText(entra.getCodigo());
       // entra.setIdProveedor(String.valueOf(jtxentrada.getItemAt(jtxentrada.getSelectedIndex()).getIdProveedor()));
        txtsubtotal.setText(String.valueOf(entra.getSubtotal()));
        txtTOTAL.setText(String.valueOf(entra.getTotal()));
    }
        public void getCliente(){
        ClienteDAO clientDAO = new ClienteDAO();
        List<Cliente> client = clientDAO.listar();

        jtxidcliente.removeAllItems();
        for(Cliente cli:client){
            jtxidcliente.addItem(new Cliente(cli.getIdCliente(), cli.getPrimerApellido()));
            //jtxentrada.addItem(new Proveedor(String.valueOf(pro.getIdProveedor()), String.valueOf(pro.getPrimerNombre())));
        }
        
    }
    
   
    
    public void getPorcentaje(){
        
        listIva.removeAllItems();
        listIva.addItem(new Iva("0%",1));
        listIva.addItem(new Iva("12%",2));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        labSubTotal = new javax.swing.JPanel();
        labTitle = new javax.swing.JLabel();
        labFecha = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        labIdCliente = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        labPrecio = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        labPorcIva = new javax.swing.JLabel();
        labCod = new javax.swing.JLabel();
        listIva = new javax.swing.JComboBox<>();
        labtotal = new javax.swing.JLabel();
        txtFecha1 = new javax.swing.JFormattedTextField();
        txtTOTAL = new javax.swing.JTextField();
        jtxidcliente = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        labSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        labSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        labSubTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labTitle.setForeground(new java.awt.Color(11, 58, 82));
        labTitle.setText("Modificar Salida");
        labSubTotal.add(labTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        labFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labFecha.setText("Fecha");
        labSubTotal.add(labFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        txtcodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        labSubTotal.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 30));

        labIdCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labIdCliente.setText("ID Cliente");
        labSubTotal.add(labIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("Cancelar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        labSubTotal.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 90, 30));

        btnGuardar1.setBackground(new java.awt.Color(11, 58, 82));
        btnGuardar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setText("Guardar");
        btnGuardar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        labSubTotal.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 90, 30));

        labPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labPrecio.setText("SubTotal");
        labSubTotal.add(labPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtsubtotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsubtotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubtotalActionPerformed(evt);
            }
        });
        labSubTotal.add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 200, 30));

        labPorcIva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labPorcIva.setText("Porcentaje IVA");
        labSubTotal.add(labPorcIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        labCod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labCod.setText("Código");
        labSubTotal.add(labCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        listIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listIvaActionPerformed(evt);
            }
        });
        labSubTotal.add(listIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 100, 30));

        labtotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labtotal.setText("Total");
        labSubTotal.add(labtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        txtFecha1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtFecha1.setText("dd/MM/yyyy");
        txtFecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFecha1ActionPerformed(evt);
            }
        });
        labSubTotal.add(txtFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 190, 30));

        txtTOTAL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTOTAL.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTOTALActionPerformed(evt);
            }
        });
        labSubTotal.add(txtTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 200, 30));

        jtxidcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxidclienteActionPerformed(evt);
            }
        });
        labSubTotal.add(jtxidcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        
        Entrada entra = new Entrada();
        EntradaDAO entraDAO = new EntradaDAO();
        
        if(!txtcodigo.getText().equals("") && //!txtIdProve.getText().equals("") && 
                !txtsubtotal.getText().equals("") && 
                !txtFecha1.getText().equals("")&& 
                !txtFecha1.getText().equals("dd/MM/yyyy")){
            //asaisas
           entra.setCodigo((String)txtcodigo.getText());
            //entra.setIdProveedor(String.valueOf(txtIdProve.getText()));
            entra.setIdProveedor(String.valueOf(jtxidcliente.getItemAt(jtxidcliente.getSelectedIndex()).getIdCliente()));
             entra.setIdProveedor(String.valueOf(idCliente));
            entra.setSubtotal(Float.parseFloat(txtsubtotal.getText()));
            entra.setValorIva((int) listIva.getItemAt(listIva.getSelectedIndex()).getValor());                      
            LocalDate fecha = LocalDate.parse(txtFecha1.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy")); 
            entra.setFechaEntrada(fecha);                     
                entra.setEstado(1);
                entra.setFechaModifica(LocalDateTime.now());
                entra.setUsuarioModifica(sysUser.getUsername());
                            
                if(txtcodigo.getText().length() == 5){
                    if(entraDAO.modificar(entra)){                           
                        this.dispose();
                        formProductos.getProductos();

                    }else{
                        JOptionPane.showMessageDialog(null, "No se guardaron los datos.");
                    }
                }else{
                
                    JOptionPane.showMessageDialog(null, "El código no puede superar los 5 dígitos.");
                } 
                        
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos del formulario.");
        }
        
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void txtsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubtotalActionPerformed

    private void txtTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTOTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTOTALActionPerformed

    private void jtxidclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxidclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxidclienteActionPerformed

    private void listIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listIvaActionPerformed

    private void txtFecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFecha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecha1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formRegistroSalidasEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formRegistroSalidasEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formRegistroSalidasEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formRegistroSalidasEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRegistroSalidasEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<Cliente> jtxidcliente;
    private javax.swing.JLabel labCod;
    private javax.swing.JLabel labFecha;
    private javax.swing.JLabel labIdCliente;
    private javax.swing.JLabel labPorcIva;
    private javax.swing.JLabel labPrecio;
    private javax.swing.JPanel labSubTotal;
    private javax.swing.JLabel labTitle;
    private javax.swing.JLabel labtotal;
    private javax.swing.JComboBox<Iva> listIva;
    private javax.swing.JFormattedTextField txtFecha1;
    private javax.swing.JTextField txtTOTAL;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtsubtotal;
    // End of variables declaration//GEN-END:variables
}
